import yaml

with open("color-mapping.yml", "r") as fh:
  color_mapping = yaml.load(fh, Loader=yaml.CLoader)

def resolve_color(color_name):
  global color_mapping
  if color_name.startswith("#") or color_name.startswith("oklch"):
    return color_name
  else:
    return color_mapping["theme-colors"][color_name]

with open("packages/library/src/styles/colors.css", "w") as out_fh:
  print("/* THIS FILE CODE GENERATED BY generate_colors_css.py */", file=out_fh)
  print(":root {", file=out_fh)

  for (semantic_name, color_definition) in color_mapping["semantic-colors"].items():
    light_color = resolve_color(color_definition["light"])
    dark_color = resolve_color(color_definition["dark"])
    print(f"\t--json-dive-color-{semantic_name}: light-dark({light_color}, {dark_color});", file=out_fh)

  print("}", file=out_fh)
