# https://turborepo.com/docs/guides/ci-vendors/github-actions

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  check-types:
    name: Check types
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Fix up internal dependency versions
        run: bash scripts/star_versions.sh

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run check-types
